# Generated by Django 2.2 on 2022-04-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banana_vacations_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_text', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_entry', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('planner_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banana_vacations_api.PlannerNotes')),
            ],
        ),
    ]
